[project]
name = "scrathed-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.3.0",
    "streamlit>=1.46.0",
    "tiktoken>=0.9.0",
    "torch>=2.7.1",
]
